export const theme = {
  colors: {
    yellowColor: 'rgb(245, 203, 17)',
    whiteColor: '#FFFFFF',
    grayColor: '#afafaf',
    mediumGrayColor: '#c3c3c3',
    darkGrayColor: '#545454',
    GrayMetalicColor: '#747171',
    blackColor: '#111',
    backgroundEffectBlur: '#0e0d0d',
    boxColor: '#cf9900',
    backgroundGradientGray: 'linear-gradient(to left, #afafaf, #545454)',
  },
  fonts: {
    family: {
      default: "'Open Sans', sans-serif",
      secondary: "'Raleway', sans-serif",
    },
    sizes: {
      xxxsmall: '0.2rem',
      xxsmall: '0.4rem',
      xsmall: '0.8rem',
      small: '1.6rem',
      medium: '2.4rem',
      large: '3.2rem',
      xlarge: '4.0rem',
      xxlarge: '4.8rem',
      huge: '5.6rem',
      xhuge: '6.4rem',
      xxhuge: '7.2rem',
      xxxhuge: '8.0rem',
    },
  },
  media: {
    //tem até 768px:
    lteMedium: '(max-width: 768px)',
  },
  spacings: {
    xxxsmall: '0.2rem',
    xxsmall: '0.4rem',
    xsmall: '0.8rem',
    small: '1.6rem',
    medium: '2.4rem',
    large: '3.2rem',
    xlarge: '4.0rem',
    xxlarge: '4.8rem',
    huge: '5.6rem',
    xhuge: '6.4rem',
    xxhuge: '7.2rem',
    xxxhuge: '8.0rem',
  },
};
