export const postGradutationTitles = [
  'atendimento educacional especializado',
  'arte e cultura afro-brasileira na educação',
  'arte da educação',
  'direito educacional',
  'educação musical e ensino da arte',
  'educação positiva',
  'educação especial com ênfase em múltiplas deficiências',
  'educação especial com ênfase em em TGD e superdotação',
  'ensino da matemática na educação infantil e séries iniciais',
  'neurociências e aprendizagem',
  'neuropsicopedagogia',
  'pedagogia humanísticas',
  'psicopedagogia institucional',
  'formação para educação a distância',
  'ludopedagogia',
  'orientação, supervisão e inspeção escolar',
  'pedagogia da cooperação e metodologias colaborativas',
];
